### ISSUE TITLE
Can't import types

### ISSUE THREAD

**Issue by gatoenano** [rubiin/nestjs-cloudinary#3]
### Describe the bug

Hi there!  👋

Firstly, thank you very much for your efforts in providing such a package for NestJS. 

Secondly, I just wanted to ask for the use of the Types returned by the methods. I'm probably wrong, but it seems that the types are not well exported, since I can't import them to use them. For example: 

![image](https://user-images.githubusercontent.com/2183987/232207880-d7f53649-11dc-4c3d-a0ff-8d712b49c97d.png)

I tried to import from `import { CloudinaryService, IFile } from 'nestjs-cloudinary';` but no luck. 

Maybe I'm missing something. 

Thanks in advance, cheers!

### Reproduction

Just try to import one of the types that any method can return

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 3.43 GB / 15.42 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.39)   
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/rubiin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/rubiin/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rubiin** [comment]
The types you are looking for can be imported from `import { ResourceType, UploadApiErrorResponse, UploadApiOptions, UploadApiResponse, v2 as cloudinary } from 'cloudinary';`

**Comment by rubiin** [comment]
Feel free to open the issue if issue persists

**Comment by gatoenano** [comment]
Hi @rubiin thank you very much for your response. 

Ok I'll try it then, I thought that the types could be imported from the package.

Thank you! :D
